### PR TITLE
CB-8636 Remove FEATURE_SPECIAL_PARAMS from feature.variables list

### PR DESCRIPTION
**Pull request by omefire**
CB-8636 Remove FEATURE_SPECIAL_PARAMS from feature.variables list

### CODE REVIEW

**Comment by omefire** [comment]
@vladimir-kotikov , could you please review this ?

**Comment by gorkem** [comment]
Should we close this? #182 removes all this

**Comment by omefire** [comment]
Yes, the pull request https://github.com/apache/cordova-lib/pull/182 makes these changes unecessary.

**Comment by nikhilkh** [comment]
Please close this PR if #182 supersedes this.

**Comment by omefire** [comment]
Not until PR #182 goes in !

**Comment by omefire** [comment]
Let's wait until PR #182 goes in !

**Comment by omefire** [comment]
closing this PR because #182 went in.

**Comment by vladimir-kotikov** [comment]
@omefire Could you please delete MSOT branch as well.

**Pull request closed without merging**
