### PR TITLE
CB-9354 Fix array merging with complex items

### PR DESCRIPTION
**Pull request by m1r4ge**
The issue corresponding to this PR [CB-9354](https://issues.apache.org/jira/browse/CB-9354).

### CODE REVIEW

**Comment by machty** [comment]
+1, fixes the issue for me

**Comment by psychowico** [comment]
can you merge this, plz? very annoying bug.

**Comment by KonradFak** [comment]
+1, waiting for merge

**Comment by m1r4ge** [comment]
@vladimir-kotikov It's seemed to me that I tried that method and it didn't work properly. Now everything works fine. Thx for clarifications. I'll file Aache ICLA soon.

**Comment by vladimir-kotikov** [comment]
his was merged in https://github.com/apache/cordova-lib/commit/b0c196510aa73b3ef0752c78f06e2a99afe04a95. @m1r4ge, could you please close this PR.

**Comment by m1r4ge** [comment]
Closed. Thank you Vladimir.

**Comment by gregavola** [comment]
Sorry to comment here - but how I can update my version of Cordova-Lib to support this change?

**Comment by vladimir-kotikov** [comment]
@gregavola, this change has not released yet, so you have to wait for next cordova release.

As an option you could try to clone this repository and link cordova-lib to your existing cordova installation. However this scenario is not supported and may have some negative consequences.

**Comment by revolunet** [comment]
thanks 👍

**Pull request closed without merging**
