### PR TITLE
Do not run legacy hooks from dirs anymore

### PR DESCRIPTION
**Pull request by raphinesse**
### Motivation and Context

Support for the `hooks` and `.cordova` dirs has long been deprecated or dropped but `HooksRunner` still has code to support them. This PR removes that code.

### Testing

Automated tests are passing

### CODE REVIEW

**Comment by raphinesse** [comment]
@erisu Yes, I wanted to include a note about the docs too, but I forgot. Thanks for adding it.

**Comment by rodrigograca31** [comment]
This just caused me problems.
My app relies on 2 hooks.
- Minify code.
- Filter the files that make it to the final .apk

What can I do to solve this? is there a flag to activate hooks again?

**Comment by rodrigograca31** [comment]
Seems plugins can run hooks (didnt know)

Then a possible solution is: make my own plugin with the hooks I had in the folder?

**Comment by raphinesse** [comment]
https://cordova.apache.org/docs/en/dev/guide/appdev/hooks/index.html#ways-to-define-hooks

**Comment by rodrigograca31** [comment]
thanks @raphinesse 

Spend the last 24 hours converting my hooks to this format. 
almost finished now!

**Comment by raphinesse** [comment]
I'm glad I could help you @rodrigograca31.

BTW: I actually wrote [a plugin to exclude files from the build](https://github.com/raphinesse/cordova-plugin-exclude-files). Maybe it solves your problem too.

**Comment by rodrigograca31** [comment]
Awesome! I also wrote one but nobody uses and it's outdated:
https://www.npmjs.com/package/cordova-x-filter

But thanks for sharing!

**Pull request merged**
