### PR TITLE
CB-8227 CB-8237 CB-8238 Add --save option to 'cordova platform add', 'cordova platform remove' and 'cordova platform update'

### PR DESCRIPTION
**Pull request by omefire**
CB-8227 CB8237 CB-8238
Add --save option to 'cordova platform add',
     'cordova platform remove' and 'cordova platform update'

### CODE REVIEW

**Comment by omefire** [comment]
@gorkem , plz review

**Comment by omefire** [comment]
working on fixing merge conflicts. will update this once that's done.

**Comment by gorkem** [comment]
@omefire can we enhance this to do the save if config_json has an auto_save option on regardless of the --save flag on the command. I will remove the corresponding functionality from https://github.com/apache/cordova-lib/pull/143 because I think this is a better place for it.

**Comment by gorkem** [comment]
@omefire Do you have a corresponding PR for plugins? Do you plan to create one?

**Comment by omefire** [comment]
@gorkem, I agree with doing the save if config_json has an auto_save option. that's what I was working on adding, unless you want to take it on. :)

**Comment by gorkem** [comment]
No, just go ahead..

**Comment by omefire** [comment]
@gorkem I''m planning on adding corresponding PR's for plugins.

**Comment by omefire** [comment]
I have made the following modifications :
- added support for autosave as suggested by Gorkem
- refactored --save feature to blend into the new code
- fixed a bug on autosave/--save for folders and git urls

**Comment by omefire** [comment]
related PR: https://github.com/apache/cordova-cli/pull/203

**Comment by omefire** [comment]
appveyor failed because "Build execution time has reached the maximum allowed time for your plan (40 minutes)."

**Comment by omefire** [comment]
@agrieve and @gorkem, plz review.

**Comment by gorkem** [comment]
@omefire Squash this to a single one commit? It will be easier for me to take it into the rest of the save restore changes.

**Comment by agrieve** [comment]
@omefire be sure to review yourself before asking someone else to. The "Files Changed" tab hardly even loads the diff is so big!

**Comment by purplecabbage** [comment]
The fact that the tests cannot run in the allotted 40 minutes means there is an error in the tests.
I would dump all the jshintrc related commits into another pr. 
Also, I'm not crazy about the whole single quote to double quote thing.  jshintrc wasn't even complaining about it.

**Comment by omefire** [comment]
@agrieve , sorry. I ran into an issue with git refusing to do a rebase : http://stackoverflow.com/questions/14410421/git-rebase-merge-conflict-cannot-continue.

So, I did a merge, and it lead to huge diff.

Anyway, I squashed things down to a single commit. Will you now review ? :)

**Comment by omefire** [comment]
@purplecabbage , yes there were errors in the tests but those were not related to these changes and those tests only occasionally fail in appveyor while travis passes.

what single quote are you referring to ?

**Comment by purplecabbage** [comment]
The single/double quote and jshintrc changes were showing as part of this pr. After the squash it is all okay.

**Comment by omefire** [comment]
Hey @gorkem, the commits have been squashed.

**Comment by gorkem** [comment]
@omefire I am integrating your changes to mine to implement the full circle. One thing that I have noticed  this does not support the url based case for instance the 'cordova platform add https://github.com/apache/cordova-android.git –save'. Do you want to add support for that case?

Also do you hangout on the cordova irc channel?

**Comment by omefire** [comment]
Hey @gorkem, I just tested 'cordova platform add https://github.com/apache/cordova-android.git --save', and it works for me. did you make sure to use two dashes instead of one ?

**Comment by omefire** [comment]
asdf

**Comment by vladimir-kotikov** [comment]
Confirm, adding platform by git url works fine.
Code LGTM, and also if no one has anything against the design of this, i would like to merge these chages.

**Comment by gorkem** [comment]
IMHO it is(or was) premature to drop this single PR by itself to master. This new flag --save flag should replace the save command, save command is not removed by this PR. Consequently the existing tests for save command should also be modified/replaced to work with this new function.

Also without the corresponding restore functionality --save is useless to CLI users. I think we should refrain from releasing it until restore is taken to master too

**Comment by omefire** [comment]
Hey @gorkem, I'm finalising a PR to remove the save command and add/update the tests.

**Comment by gorkem** [comment]
Already done most of it un https://github.com/gorkem/cordova-lib/tree/save_restore_final and https://github.com/gorkem/cordova-cli/tree/save_restore_final.. 
Still missing --save flag implementation for plugins and tests.

**Pull request merged**
