### PR TITLE
CB-9815 Engine name="cordova" should check tools version, not platforms

### PR DESCRIPTION
**Pull request by sgrebnov**
https://issues.apache.org/jira/browse/CB-9815

### CODE REVIEW

**Comment by TimBarham** [comment]
This gives us the correct behavior, but are there backwards compatibility issues (is it likely any plugin is using this expecting the current behavior)?

**Comment by sgrebnov** [comment]
@TimBarham I see your point, but all places where I saw that engine name usage all devs thought they check cordova version - see examples below. Taking into account that we will apply this change only in next/future cordova version where we have pinned platforms versions lower than cordova version itself  non of existing plugins will be broken.

Also, I see that this is not covere in docs at all so we may want to contribute some info to Plugin Dev Guide 

InAppBrowser plugin
```
    <engines>
      <engine name="cordova" version=">=3.1.0" /><!-- Needs cordova/urlutil -->
    </engines>
```
phonegap-facebook-plugin
```
    <engines>
        <!-- Requires > 3.3.* because of the custom Framework tag for iOS [CB-5238] -->
        <!-- Requires > 3.5.0 because of the custom Framework tag for Android [CB-6698] -->
        <engine name="cordova" version=">=3.5.0" />
    </engines>
```

**Comment by TimBarham** [comment]
Yeah, sounds reasonable. :+1:

**Comment by nikhilkh** [comment]
LGTM

**Pull request closed without merging**
