### PR TITLE
Cb 7183

### PR DESCRIPTION
**Pull request by bso-intel**
CB-7183 security check for the scriptSrc property of the engine tag.

The other src and target-dir path escape checks are already implemented in 
cordova-lib/src/plugman/platforms/common.js/copyFile() function.
The only missing security check is in the scriptSrc of the \<engine\> tag.

### CODE REVIEW

**Comment by bso-intel** [comment]
Hi Shazron,
Could you review this CB-7183?
As we discussed we need some security check for plugins accessing outside the plugins directory.
Please pull if it looks okay.
Thanks.

**Comment by shazron** [comment]
Hi,
I'll look at this today.

**Comment by shazron** [comment]
Squashed all your commits and reviewed them -- seems a minimal change. I'd like to get this in, but please add a failing test first in https://github.com/apache/cordova-lib/blob/master/cordova-lib/spec-plugman/install.spec.js

**Comment by bso-intel** [comment]
Hi Sharon,
Thanks for reviewing.
I don't see any failures for the test.
{quote}
[cordova-lib] node_modules/jasmine-node/bin/jasmine-node spec-plugman/install.spec.js 
........................

Finished in 1.84 seconds
24 tests, 35 assertions, 0 failures, 0 skipped
{quote}

It seems CIs also show all checks passed.
Could you tell me how to reproduce the error you are seeing for the install.spec.js?

**Comment by shazron** [comment]
I meant, you have to *add* a failing test. Your change did not include a test.

**Comment by bso-intel** [comment]
Got it. Sorry.
I will add a unit test that detects the path escaping issue, and let you know.

**Comment by bso-intel** [comment]
Hi Shazron,

I added a unit test that detects the security violation.

**Comment by shazron** [comment]
Thanks! :) I'll review, test and pull in if all goes well.

**Comment by bso-intel** [comment]
Thanks for merging, Shazron!!

**Pull request closed without merging**
