### PR TITLE
CB-9371: Fix prepare deleting orientation preferences

### PR DESCRIPTION
**Pull request by cjpearson**

### CODE REVIEW

**Comment by christoph-neumann** [comment]
This is a needed fix! Why has this not been merged?

**Comment by chrskrchr** [comment]
Agreed - this is a useful change.  I want to be able to specify different orientation settings for iPhone vs. iPad at the Xcode project level, and this change would allow me to do that without Cordova clobbering my project-level settings.

**Comment by mattrayner** [comment]
Is there any news on this?

**Comment by mattrayner** [comment]
I'm guessing there's no news on this?

**Comment by cjpearson** [comment]
@shazron, could you please take a look at this PR?

**Comment by shazron** [comment]
@cjpearson unfortunately this patch can't be applied since the code has changed. Can you re-work it based on the master code? Also, the code you are trying to patch is the default fallback if a platform does not conform to the Platform API (older platforms). For newer platforms that do, like cordova-ios@4.x, they have their own Platform API implementations -- so the corresponding code would exist here: https://github.com/apache/cordova-ios/blob/08e00b68efbf2bfee21866f0bedd9c01ee8255e5/bin/templates/scripts/cordova/lib/prepare.js#L252-L275

**Comment by cjpearson** [comment]
Thanks, @shazron. I've rebased this pr and opened a new one here https://github.com/apache/cordova-ios/pull/233

**Comment by stevengill** [comment]
I believe we are deleting ios_parser.js for cordova@7 since that functionality has all been moved into  cordova-ios platform now. This would only be useful for older versions of cordova-ios (pre-API.js) now and we are dropping support for those older versions in cordova-7. I think this PR can be closed.

Thoughts @shazron?

**Comment by shazron** [comment]
I think we can close this since its already in the Platform API for cordova-ios, and users will have to upgrade if they want this fix for cordova-ios < 4.

**Pull request closed without merging**
