### PR TITLE
CB-11134: Removing duplicated warning

### PR DESCRIPTION
**Pull request by riknoll**

### CODE REVIEW

**Comment by omefire** [comment]
LGTM!

**Comment by omefire** [comment]
(Though not related to this change) it seems like the ```--force``` flag wouldn't work as advertised ?

**Comment by riknoll** [comment]
@omefire you are correct. That flag seems to be totally broken

**Comment by omefire** [comment]
Ok. I've created an issue to track it here: https://issues.apache.org/jira/browse/CB-11219

**Pull request merged**
