### PR TITLE
CB- 12017: update npm dependencies

### PR DESCRIPTION
**Pull request by audreyso**
### What does this PR do?
Updates npm dependencies used in cordova-lib.

### Checklist
- [X] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [X] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [X] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by audreyso** [comment]
still need to update at elementtree, jshint, q, and shelljs --> when updated will cause tests to fail

**Comment by stevengill** [comment]
@audreyso can you rebase this from master?

**Comment by audreyso** [comment]
@stevengill yes ...done!

**Comment by stevengill** [comment]
merged

**Pull request closed without merging**
