### PR TITLE
CB-8633 BugFix: Support for urls to tarballs was broken

### PR DESCRIPTION
**Pull request by omefire**
CB-8633 BugFix: Support for `urls to tarballs` was broken

### CODE REVIEW

**Comment by nikhilkh** [comment]
Can we add tests for this scenario? This looks like a regression and there is not test coverage for this scenario.

**Comment by omefire** [comment]
Yes, I have plans to add automated tests for this scenario. 

I had some tests for this scenario a while back : https://github.com/apache/cordova-lib/commit/9079bb8560615572b571924b908b0124a2845a2e#diff-17ad7ab65fc264c2d2d1792c17468c6aR517
Unfortunately, they were removed because of complains those tests made refactoring the code harder.

I do intend to reintroduce them as integration tests this time, instead of as unit tests. Hopefully, there's not gonna be concerns this time around. Let's see.

**Comment by omefire** [comment]
@agrieve , Please, could you review this and potentially merge this ? It fixes a regression that appeared after recent refactoring in `cordova platform add` functionality.

**Comment by omefire** [comment]
@vladimir-kotikov

**Comment by vladimir-kotikov** [comment]
Tested, works fine. LGTM.

**Pull request merged**
