### PR TITLE
CB-9964 - Add --template to create command

### PR DESCRIPTION
**Pull request by dubeejw**
When providing a --template argument during project creation, users can use templates apps from a local directory, GitHub, or NPM. This makes sharing templates, and example apps much easier.

When using a GitHub URL, the user may specific a branch to pull from by appending a "#" followed by a tag name to the Git URL.

A version can also be supplied by the user when fetching a template from NPM. This may be done by appending a "@" followed by the NPM version to the NPM package name. 


### CODE REVIEW

**Comment by dubeejw** [comment]
Test failures are related to cordova-common, which was not modified in this code.

**Comment by vladimir-kotikov** [comment]
The failing test fixed in https://github.com/apache/cordova-lib/commit/6c31f4717a00a540ea9782a1543bce6dd72888f1.

**Comment by dubeejw** [comment]
New unrelated tests failing.

**Comment by dubeejw** [comment]
All test passing after pulling latest changes from Master.

**Pull request closed without merging**
