### PR TITLE
CB-8978 Added new image element tag for config.xml

### PR DESCRIPTION
**Pull request by ktop**

### CODE REVIEW

**Comment by purplecabbage** [comment]
Please start a discussion for this here:
https://github.com/cordova/cordova-discuss/issues
This should NOT be merged without some justification of why we need it, and why it belongs in config.xml, ...

**Comment by jcesarmobile** [comment]
the discusion already started on the mail list
http://markmail.org/message/yx3pvydgyxpssgas
But it didnt get any conclusion

I still don't see why would a regular cordova developer use native images on a regular project

**Comment by ktop** [comment]
I'll move the discussion to the right place.

**Comment by purplecabbage** [comment]
Thanks Karen.
You weren't doing it in the wrong spot, we are just trying out some new
ways of discussing feature additions.

@purplecabbage
risingj.com

**Comment by stevengill** [comment]
I've merged https://github.com/apache/cordova-lib/pull/468 in. @ktop can you close this PR?

**Comment by ktop** [comment]
Yep, thanks.

**Pull request closed without merging**
