### PR TITLE
Adds copying of blackberry10 splashscreens - fixes CB-9653

### PR DESCRIPTION
**Pull request by timwindsor**
Only icons were getting copied before.

### CODE REVIEW

**Comment by timwindsor** [comment]
I don't think the checks are relevant to the code changed.

**Comment by vladimir-kotikov** [comment]
@timwindsor, the failing test fixed in https://github.com/apache/cordova-lib/commit/6c31f4717a00a540ea9782a1543bce6dd72888f1. Just to be sure you could trigger the build again

**Comment by timwindsor** [comment]
Thanks @vladimir-kotikov, it's working now.

**Comment by kdubuc** [comment]
You plan to merge it ? :suspect:

**Comment by kdubuc** [comment]
Thanks :wink:

**Pull request closed without merging**
