### PR TITLE
CB-8634 : `cordova platform add git_url#custom_branch` support for custom branches

### PR DESCRIPTION
**Pull request by omefire**
CB-8634 : `cordova platform add git_url#custom_branch` support for custom branches

### CODE REVIEW

**Comment by omefire** [comment]
Yes, it does need to be documented : https://github.com/apache/cordova-cli/pull/210

**Comment by omefire** [comment]
@vladimir-kotikov

**Comment by vladimir-kotikov** [comment]
LGTM

**Comment by omefire** [comment]
This change was merged in.

**Pull request closed without merging**
