### PR TITLE
CB-11653 copied findProjectRoot from cordova-lib

### PR DESCRIPTION
**Pull request by carynbear**
… over

### CODE REVIEW

**Comment by stevengill** [comment]
Two things:

1) migrate the tests over and add them to this pr
2) add the apache license header comment to the top. You will notice every other file has this. Apache requirement.

**Comment by carynbear** [comment]
Done

**Comment by stevengill** [comment]
LGTM

**Comment by stevengill** [comment]
Can you create a issue to remove the duplicate code + tests from cordova-lib. That can be a separate PR after cordova-common has been released.

**Comment by stevengill** [comment]
@vladimir-kotikov any issues you see with us moving this from cordova-lib to cordova-common?

**Comment by carynbear** [comment]
@stevengill https://issues.apache.org/jira/browse/CB-11654

**Comment by vladimir-kotikov** [comment]
@stevengill, @carynbear, no issues. Just curious where do you plan to use it outside of cordova-lib :)

**Comment by carynbear** [comment]
I would like to use it in Phonegap, but also it seems like a useful method in general for dealing with Cordova projects. In the spirit of modularizing Cordova, it seems that Plugman would be a potential use case if it is broken out.

**Comment by vladimir-kotikov** [comment]
Ah, I see, thanks!

**Pull request closed without merging**
