### PR TITLE
CB-10694 - Platform-specific configuration preferences don't override global settings

### PR DESCRIPTION
**Pull request by shazron**
Includes jasmine test.

### CODE REVIEW

**Comment by stevengill** [comment]
LGTM

**Comment by riknoll** [comment]
What's up with the Appveyor build on this?

**Comment by shazron** [comment]
The truncated AppVeyor message says "AppVeyor was unable to build non-mergeable pull request", which is odd since there are no conflicts (as reported by Github)

**Comment by riknoll** [comment]
Yeah, that is weird. Probably not an issue

**Comment by riknoll** [comment]
LGTM

**Comment by csantanapr** [comment]
LGTM

**Pull request merged**
