### PR TITLE
Cleanup pkgJson-restore.spec

### PR DESCRIPTION
**Pull request by raphinesse**
Only the `pkgJson-restore.spec` part of #629 as requested by @brodybits. See #629 for a full description.

### CODE REVIEW

**Comment by raphinesse** [comment]
Thanks for the quick approval @brodybits :+1: 

Now there's some unrelated tests failing again. This really starts to piss me off... :unamused:

**Comment by brodybits** [comment]
> Now there's some unrelated tests failing again.

I spotted that too, looks like something flakey. Definitely not the first time.

**Comment by raphinesse** [comment]
A quick bisect says it was me in 60ba43944927c41b587d179639472253aaf0d47f

**Comment by brodybits** [comment]
> A quick bisect says it was me in 60ba439.

Wonder if we should start to get rid of Q while you are at it?

**Comment by raphinesse** [comment]
> Wonder if we should start to get rid of Q while you are at it?

I have a local branch for that and it's definitely not something to do while we're at something else. There are various blockers.

**Comment by raphinesse** [comment]
Merged as CI failures were unrelated

**Pull request merged**
