### PR TITLE
Cleanup pkgJson.spec

### PR DESCRIPTION
**Pull request by raphinesse**
Only the `pkgJson.spec` part of #629 as requested by @brodybits. For further information see #629.

This commit does not drop any test cases. However, it fixes various bugs
in the existing expectations and often asserts stronger expectations
than the original tests.

Changes include:

- DRY code
- Improve formatting
- Reduce excessive comments
- Simplify platform list generation
- Wrap all tests in common describe to allow common setup/teardown
- Use a fresh tmpDir for every test to avoid caching issues
- Use fs-extra for setup/teardown
- FIX Wait for promise
- Properly set default timeout for the whole suite
- Don't symlink into fixtures
- Sane config file handling
- Remove event listeners on teardown
- Re-enable disabled test 005 that was fixed by #628
- Do not quote props when not needed
- Do not pass array when we only have scalar
- Nicer imports
- Save test platforms/plugins as constants

### CODE REVIEW

**Comment by raphinesse** [comment]
There's a verbose version of this at https://github.com/apache/cordova-lib/compare/master...raphinesse:verbose-pkgJson-spec-cleanup. It is not up-to-date though. Will try to change that for better reviewability.

**Comment by brodybits** [comment]
> There's a verbose version of this at https://github.com/apache/cordova-lib/compare/master...raphinesse:verbose-pkgJson-spec-cleanup.

I have already made my own rebase at <https://github.com/brodybits/cordova-lib/compare/honest-specs...brodybits:verbose-cleanup-updated> and captured the remaining diffs in <https://github.com/brodybits/cordova-lib/compare/verbose-cleanup-rebased...verbose-cleanup-updated>, should be good enough for me to check the changes. I will use `git show -b` whenever needed (first commit in your verbose branch). I will do the review sometime today.

**Comment by raphinesse** [comment]
@brodybits Thanks! :+1: Overall, what's going on is very similar to the `pkgJson-restore.spec` cleanup

**Comment by brodybits** [comment]
Approved with a couple ideas for followup fixes:

I think it would be nice to use `fs.readJsonSync()` instead of `requireNoCache()`, like you had proposed in PR #645. The following did not seem to break any tests on my local machine:

```diff
--- a/integration-tests/pkgJson.spec.js
+++ b/integration-tests/pkgJson.spec.js
@@ -72,7 +72,7 @@ describe('pkgJson', function () {
     function pluginVersion (pluginName) {
         const p = path.join(project, 'plugins', pluginName, 'package.json');
         expect(p).toExist();
-        return requireNoCache(p).version;
+        return fs.readJsonSync(p).version;
     }
 
     function getPkgJson (propPath) {
@@ -81,7 +81,7 @@ describe('pkgJson', function () {
         return keys.reduce((obj, key) => {
             expect(obj).toBeDefined();
             return obj[key];
-        }, requireNoCache(pkgJsonPath));
+        }, fs.readJsonSync(pkgJsonPath));
     }
 
     function getCfg () {
```

I personally find this kind of construct from using `const`s to be a little bit ugly:

```js
            expect(getPkgJson('dependencies')).toEqual({
                [PLUGIN]: '^3.2.2',
                [`cordova-${PLATFORM}`]: '^4.5.4'
            });
```

I would personally favor adding another `const` declaration, maybe something like `CORDOVA_PLATFORM_ID`.

**Comment by raphinesse** [comment]
Thanks so much for taking the time to review these huge change sets, @brodybits.

I'll prepare a PR for your first suggestion right away. The second one might be fitting to be resolved in a planned update.

**Pull request merged**
