### PR TITLE
CB-12385: (win32/linux/darwin) auto open devtools in chrome for cordova-serve

### PR DESCRIPTION
**Pull request by botcheddevil**
### Platforms affected
linux, win32, darwin

### What does this PR do?
Automatically open the devtools for developer

### What testing has been done on this change?
chrome on darwin has been tested.

### Checklist
- [ Y ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ Y ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by stevengill** [comment]
Thanks for sending the PR! 

I think this would be better as a flag. `cordova serve --devtools`. 

We can add it to opts as a boolean and pass that into getBrowser function.

**Comment by purplecabbage** [comment]
This is interesting, is it possible in other brower targets?

**Comment by purplecabbage** [comment]
cordova-serve now lives in it's own repo at 
github.com/apache/cordova-serve

**Comment by raphinesse** [comment]
If someone needs this, they should open an issue/PR in [apache/cordova-serve](https://github.com/apache/cordova-serve).

Closing this PR as it's outdated.

**Pull request closed without merging**
