### PR TITLE
CB-9712 CLI 5.3 breaks with node 3.3.3

### PR DESCRIPTION
**Pull request by daserge**
I could repro the issue using npm@3.3.6 as npm@3.3.5 seems to have issues with Cordova installation.

Requires [cordova-app-hello-world#14](https://github.com/apache/cordova-app-hello-world/pull/14) changes in order for require to work.

[Jira issue](https://issues.apache.org/jira/browse/CB-9712)

### CODE REVIEW

**Comment by daserge** [comment]
Tests are passing with the updated cordova-app-hello-world: #317

**Comment by nikhilkh** [comment]
LGTM. @stevengill for FYI. Next tools release will have to also release cordova-app-hello-world to make this work.

**Comment by stevengill** [comment]
LGTM. We should do a new release soon!

**Comment by nikhilkh** [comment]
@daserge Does the dev workflow break with this change? Does `coho npm-link` need to be modified to include linking cordova-app-hello-world for cordova committers who are linking to cloned version of the repo for this to work.

**Comment by daserge** [comment]
@nikhilkh yes I think coho will need an update.
Although I still have issues with local dev deployment specifically with [npm linking](https://github.com/npm/npm/issues/9766) so can't verify this for now.

**Comment by nikhilkh** [comment]
Let's check this in anyway.

**Comment by omefire** [comment]
I don't understand. Why would we need a new release of 'cordova-app-hello-world' for this to work ? This code doesn't seem to require anything extra as it currently stands.

**Comment by daserge** [comment]
This update needs [cordova-hello-world-module to export its path](https://github.com/apache/cordova-app-hello-world/pull/14/files#diff-168726dbe96b3ce427e7fedce31bb0bcR3) as its used in `cfg.lib.www.url` assignment directly. 
Probably I should add a comment to this line for clearness.
Alternatively we can use [require.resolve](https://nodejs.org/api/globals.html#globals_require_resolve) here instead - what do you think?

**Comment by nikhilkh** [comment]
`require.resolve` seems a more elegant way to handle this. As long as that is supported in older versions of node.

**Comment by daserge** [comment]
And actually the reason why this does not work with old `cordova-hello-app-world` is the fact that it did not have an entry point (index.js).

**Comment by omefire** [comment]
@nikhilkh , but us using ```require.resolve``` here doesn't make it necessary to update the hello-world app.

**Comment by omefire** [comment]
@daserge , Aha! that was a question I asked myself. I didn't see any entry point and assumed node.js figures it out via some weird rules.

Can we also update package.json in the hello-world app to explicitly mention the entry point ? (index.js)

**Comment by daserge** [comment]
@omefire, thank you for the review, 
I've addressed it - exposed `cordova-app-hello-world.dirname` explicitly, also included a few places with the similar path issues.

**Comment by vladimir-kotikov** [comment]
LGTM

**Comment by omefire** [comment]
LGTM!

**Pull request merged**
