### PR TITLE
CB-9549 Removes excess JS files from browserified app 

### PR DESCRIPTION
**Pull request by vladimir-kotikov**
This PR fixes https://issues.apache.org/jira/browse/CB-9549

It also includes https://github.com/apache/cordova-lib/pull/279

### CODE REVIEW

**Comment by vladimir-kotikov** [comment]
@stevengill, please review.

**Comment by nikhilkh** [comment]
LGTM

**Comment by stevengill** [comment]
LGTM too

**Comment by purplecabbage** [comment]
+1

**Pull request merged**
