### PR TITLE
CB-10461: 'cordova platform ls' should list the versions of platforms pinned

### PR DESCRIPTION
**Pull request by sarangan12**
Added version information to available platforms list. The output will
be similar to:
E:\projects\MyApp3> cordova platform ls
Installed platforms: android 5.0.0, blackberry10 3.8.0-dev, browser
4.0.0, firefoxos 3.6.3, windows 4.2.0, wp8 (deprecated)
Available platforms: amazon-fireos ~3.6.3 (deprecated), webos ~3.7.0,
windows8 ~4.2.0

### CODE REVIEW

**Comment by sarangan12** [comment]
@dblotsky @nikhilkh @riknoll, @vladimir-kotikov Can you please review and merge this PR?

**Comment by TimBarham** [comment]
I like the idea, but find the list is starting to get a bit confusing (to see the actual platform names. We need to make sure the platform names a very easy to see. On option that might help would be to switch to using line breaks instead of commas, something like:

```
Installed platforms: browser 4.1.0-dev
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  android ~5.1.0
  blackberry10 ~3.8.0
  firefoxos ~3.6.3
  webos ~3.7.0
  windows ~4.3.0
  windows8 ~4.3.0
  wp8 ~3.8.2 (deprecated)
```

**Comment by riknoll** [comment]
That's more like what we do for plugins (`cordova plugin ls`)

**Comment by TimBarham** [comment]
Yeah, and in fact, for consistency maybe "installed platforms" should also be separated by line breaks rather than commas:

```
Installed platforms:
  android 5.1.0
  browser 4.1.0-dev
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  firefoxos ~3.6.3
  webos ~3.7.0
  windows ~4.3.0
  windows8 ~4.3.0
  wp8 ~3.8.2 (deprecated)
```

**Comment by sarangan12** [comment]
@TimBarham @nikhilkh Agreed. Added formatting changes. Now the display will be like:
Installed platforms:
        android 5.0.0
        blackberry10 3.8.0-dev
        browser 4.0.0
        firefoxos 3.6.3
        windows 4.2.0
        wp8 (deprecated)
Available platforms:
        amazon-fireos ~3.6.3 (deprecated)
        webos ~3.7.0
        windows8 ~4.2.0

**Comment by TimBarham** [comment]
Looks great! Just one comment: I think just a couple of spaces would look better than a tab.

Also, looks like there is a test that is sensitive to the output of this command.

**Pull request closed without merging**
