### PR TITLE
Remove plugin pinning

### PR DESCRIPTION
**Pull request by riknoll**
As discussed on the dev list

### CODE REVIEW

**Comment by riknoll** [comment]
I'll create a JIRA later (Apache JIRA seems to be down right now). @stevengill please review when you have a moment.

**Comment by stevengill** [comment]
LGTM

**Comment by nikhilkh** [comment]
Let's get it in! I just resolved another JIRA filed because this was causing some confusion.

**Comment by riknoll** [comment]
JIRA is [CB-10880](https://issues.apache.org/jira/browse/CB-10880). Merging now

**Pull request closed without merging**
