### PR TITLE
CB-8482: Update engine syntax within config.xml

### PR DESCRIPTION
**Pull request by omefire**
CB-8482: Update engine syntax within config.xml

- from : `<cdv:engine id="android" version="3.7.0-dev" />`
- to :      `<engine name="android" version="3.7.0-dev" />`
- updated and tested all modules that depended on old syntax

### CODE REVIEW

**Comment by omefire** [comment]
CB-8482: Update engine syntax within config.xml

- from : `<cdv:engine id="android" version="3.7.0-dev" />`
- to :      `<engine name="android" version="3.7.0-dev" />`

**Comment by gorkem** [comment]
I wonder if it is worth to do an auto convert from old syntax when we encounter it?

**Comment by omefire** [comment]
There will need to be another pass to update dependent modules to handle the possibility that some new code depending on old syntax might have been inserted in the interim. this is just a reminder to myself and the person who will merge this.

**Comment by gorkem** [comment]
@omefire this looks OK and would like to get it in. The dependencies have changed though save.js and restore.js are gone. I could not quickly spot anything on platform.js other then the current one. Can you do a rebase and double check as well.

**Comment by omefire** [comment]
@gorkem, cool. working on a rebase + update to new dependent modules ...

**Comment by omefire** [comment]
@gorkem, I did find some things that needed to be updated in restore-util.js. those have been taken care of.

**Pull request merged**
