### PR TITLE
CB-10622 fix target attribute being ignored for images in config.xml

### PR DESCRIPTION
**Pull request by andorman**

### CODE REVIEW

**Comment by nikhilkh** [comment]
@vladimir-kotikov to review

**Comment by vladimir-kotikov** [comment]
LGTM. @andorman, It'd be great if you could add a couple of tests for this?

@nikhilkh, it looks like `target` attribute for images is not documented in [Icons and Splash Screens guide](http://cordova.apache.org/docs/en/latest/config_ref/images.html). Should this be included into documentation improvements effort?

**Comment by vladimir-kotikov** [comment]
@andorman, i'll take care of tests. Thanks

**Comment by nikhilkh** [comment]
We need to add this to the docs. @andorman - Could you submit a PR to this page? https://github.com/apache/cordova-docs/blob/master/www/docs/en/dev/config_ref/images.md

**Pull request closed without merging**
