### PR TITLE
Deprecate `requireCordovaModule` for non-Cordova modules

### PR DESCRIPTION
**Pull request by raphinesse**
Addresses the deprecation part of #689.

### CODE REVIEW

**Comment by brodybits** [comment]
I just pushed a couple updates that I think are needed:
- emit deprecation warning event in case of use of `requireCordovaModule` with non-Cordova module
- fix and update spec for `requireCordovaModule`

I am about to include the deprecation warning event in the hotfix proposed in #708.

**Comment by brodybits** [comment]
@raphinesse go ahead and push your implementation. I was only doing this to help me with the hotfix.

**Comment by raphinesse** [comment]
This version is not node@4 compatible, I'm afraid. But it should be straightforward to make it compatible.

@brodybits If you want to include this in #708, I think I can whip up a commit that makes this node@4 compatible.

**Comment by brodybits** [comment]
FYI I am only using part of 1fdc38d58615e8a61accaf25b2418ba6ccd538a5 in patch PR #708. You can see it in <https://github.com/apache/cordova-lib/pull/708/commits/0b0ae7a39b34bcbe2d6aa80244c38ad3bda609d8>. The other 3 commits so far *are* part of patch #708. Please let me know if you would like me to explain this in more detail.

**Comment by raphinesse** [comment]
@brodybits I noticed it and it's fine. The bug is fixed anyway.

**Comment by raphinesse** [comment]
@brodybits Agreed. _If_ we should fork off another 8.x branch _from master_ we would need to apply something similar to #708 there too.

**Pull request merged**
