### PR TITLE
CB-9758 Mobilespec crashes adding plugins on OS X

### PR DESCRIPTION
**Pull request by daserge**
Avoid empty keys in NSExceptionDomains

[Jira issue](https://issues.apache.org/jira/browse/CB-9758)

### CODE REVIEW

**Comment by daserge** [comment]
@shazron, could you please review this?

**Comment by shazron** [comment]
Just a question, this is for the case for example: `http://*` or `https://*` correct? A failing test should be added to the existing tests.

**Comment by daserge** [comment]
The current code results in such an entry in `mobilespec-Info.plist`:
```xml
        <key></key>
        <dict/>
```
This happens with mobilespec `config.xml`' [`<allow-navigation href="data:*" />`](https://github.com/apache/cordova-mobile-spec/blob/78a865153615ae20b9d8b6305b7b1a49496bbbf7/config.xml#L55)(`scheme:*` if generalize) and also for `http://*` or `https://*`.

**Comment by daserge** [comment]
BTW `<allow-navigation href="http:*" />` and `<allow-navigation href="https:*" />` don't crash and result in 
```xml
        <key>null</key>
        <dict>
          <key>NSExceptionAllowsInsecureHTTPLoads</key>
          <true/>
        </dict>
```
and 
```xml
        <key>null</key>
        <dict/>
```
correspondingly.
Not sure if they work in this case though.

**Comment by shazron** [comment]
Great, since you've identified the stuff that crashes, you should add tests for them in the jasmine tests (there are already tests for other cases).

**Comment by daserge** [comment]
Sure, I'm looking into this.

**Comment by daserge** [comment]
@shazron, could please explain the difference in these tests? Is there a typo?
[`it('<access> - should handle wildcard')`](https://github.com/apache/cordova-lib/commit/0c3614e2fff6f3579a9220611ad439abde9abde1#diff-dfa42d6bc7630716b3099bfc4d33da05R191)
[`it('<allow-navigation> - should handle wildcard')`](https://github.com/apache/cordova-lib/commit/0c3614e2fff6f3579a9220611ad439abde9abde1#diff-dfa42d6bc7630716b3099bfc4d33da05R308)

**Comment by shazron** [comment]
No, its correct. The two tags are different.

**Comment by daserge** [comment]
Don't these tests do the same thing?
Or is there any state changing between tests I'm missing?

**Comment by shazron** [comment]
They do the same thing, almost. The only thing different is access tags do not handle wildcards in the schemes. I've opted to keep them separate for completeness, and ease of maintenance. 

Ideally the allow-navigation test should be part of the whitelist plugin, since it is only part of that.

**Comment by daserge** [comment]
Got it, thanks for the explanation, @shazron.

**Comment by daserge** [comment]
@shazron, could you please review again?

**Comment by shazron** [comment]
looks good to me. Thanks @daserge!

**Pull request closed without merging**
