### PR TITLE
CB-14194: Don't cut off scope from package identifier

### PR DESCRIPTION
**Pull request by oliversalzburg**
### Platforms affected
All

### What does this PR do?
When looking for the installation folder for a scoped npm package, include the scope in the search. Otherwise it will always fail.

### What testing has been done on this change?
I ran `npm test` and I built (`cordova prepare`) our own app with this code.

### Checklist
- [X] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [X] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by dpogue** [comment]
:+1: on this change.

I'd feel slightly more confident if there were [updated tests](https://github.com/fairmanager-cordova/cordova-lib/blob/master/spec/cordova/plugin/add.spec.js) to confirm expected behaviour and prevent regressions.

**Comment by oliversalzburg** [comment]
@dpogue Good call. I'll have a look at the tests.

**Comment by raphinesse** [comment]
How is this related to #602?

**Comment by brodybits** [comment]
@oliversalzburg I wonder if you should start with #602, fix it up, add your other enhancements, and raise a new PR that says something like "closes #602" or "resolves #602"?

**Comment by oliversalzburg** [comment]
Yeah, I'll look into it later today, but I expect that I'll also need #622 to get a working setup to even approach this, as I'm primarily working on Windows.

**Pull request closed without merging**
