### PR TITLE
CB-10459: cordova platform list should mark amazon-fireos and wp8 as deprecated

### PR DESCRIPTION
**Pull request by sarangan12**
Added depracted information to wp8 and amazon-fireos

JIRA Issue Link: https://issues.apache.org/jira/browse/CB-10459

@nikhilkh @dblotsky @riknoll Can you please review and merge this  PR?

### CODE REVIEW

**Comment by riknoll** [comment]
LGTM. My only suggestion would be that it might be nice if we grabbed the deprecation info from somewhere instead of hard coding it in that method. Is it already encoded somewhere in cordova-lib? If not, should it be? Or should it be specified in the platform somehow?

**Comment by sarangan12** [comment]
@riknoll Agreed. Moved the deprecated info to Json file

**Comment by nikhilkh** [comment]
LGTM

**Comment by sarangan12** [comment]
@riknoll Can you merge this PR?

**Comment by sarangan12** [comment]
@vladimir-kotikov Can you please review and merge this PR?

**Comment by vladimir-kotikov** [comment]
@sarangan12, LGTM, merged.

**Pull request closed without merging**
