### PR TITLE
CB-9407 Fixes incorrect applying of plugin-provided config changes.

### PR DESCRIPTION
**Pull request by vladimir-kotikov**
See [CB-9407](https://issues.apache.org/jira/browse/CB-9407) for details. This PR is an alternative to #274, reworked according to recent changes (PlatformApi).

### CODE REVIEW

**Comment by zalun** [comment]
r+ 
test on file-transform plugin under firefoxos

**Comment by zalun** [comment]
It's still not working in off the shelf cordova...

**Comment by vladimir-kotikov** [comment]
@zalun, just tried create a new blank app with file-transfer and geolocation plugins, and it seems to fork for me:

_config.xml_:
```xml
    <permission name="systemXHR" privileged="true" />
    <permission description="Required for accessing user location." name="geolocation" />
```
_manifest.webapp_:
```json
    "permissions": {
        "systemXHR": {},
        "geolocation": {
            "description": "Required for accessing user location."
        }
    }
```

Could you please double check, if the issue still exists using latest `master`?

**Comment by zalun** [comment]
master is fine, it's the Cordova 5.3.3 which still doesn't have this fix ...

**Comment by TimBarham** [comment]
@zalun - this fix will be in the next minor/major release (whichever comes first) - the only change included in 5.3.3 was a patch to support node 4.

**Pull request merged**
