### PR TITLE
CB-9901 cordova plugin search opens in a browser

### PR DESCRIPTION
**Pull request by eymorale**

### CODE REVIEW

**Comment by nikhilkh** [comment]
LGTM this is a good one to fix. There is a jshint failure though that you might want to fix.

**Comment by eymorale** [comment]
Thanks @nikhilkh! I'll take a look at the jshint failure and fix it

**Comment by omefire** [comment]
What about people who use Cordova-lib from gulp instead of the cli ?
Does it make sense to pop open a browser window ?

**Comment by eymorale** [comment]
@omefire I've started a discussion thread for this on the dev list

**Comment by TimBarham** [comment]
Are people likely to be doing a plugin search from a gulp script?

**Comment by csantanapr** [comment]
I think is a nice feature to open the browser to a good spot on the wen to search for plugins applicable  for cli use cases where people are running by hand when they get started to use the CLI. not applicable to unattended. The current form is just a mess of a UI/UX.

For scripting or unattended like gulp scripts I guess they can use npmsearh same way we are doing for the website plugin search.

**Comment by stevengill** [comment]
Lets merge this in after the 5.4.0 release

**Comment by eymorale** [comment]
sounds good. thanks @stevengill

**Pull request closed without merging**
