### PR TITLE
CB-11713 and CB-11961

### PR DESCRIPTION
**Pull request by goya**
### Platforms affected
N/A

### What does this PR do?
Fixes for the following issues:

CB-11961 do a shallow clone if git_ref is a remote ref
CB-11713 no CLI feedback on plugin version installed during plugin install

### What testing has been done on this change?
jasmine tests

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by goya** [comment]
should be fixed now.  got bit by false git documentation on git < 2

**Comment by goya** [comment]
oh well ill just leave this here until master gets working tests again.

**Comment by filmaj** [comment]
Thanks for waiting @goya ! @stevengill, @audreyso and I are working on that.

**Comment by filmaj** [comment]
@goya CI should be passing now, you'll need to rebase as a bunch of files moved around as part of the plugin command refactor and test speed improvements we landed.

The `spec-plugman/fetch.spec.js` file moved to `integration-tests/plugman_fetch.spec.js` now I believe. Worth noting that we are doing a big push to move away from I/O-heavy integration tests as much as possible, and instead write out unit tests for each module. It'd be nice if you could follow that pattern in this PR as well. I'm also happy to help with that if you want.

**Pull request closed without merging**
