### PR TITLE
CB-9311 Add support for 87x87 icon, fix reference url

### PR DESCRIPTION
**Pull request by tony--**

### CODE REVIEW

**Comment by shazron** [comment]
iOS parser code does not go into cordova-lib anymore. It goes in cordova-ios (Platform API)

**Comment by shazron** [comment]
It's possible all the work that has gone into cordova-lib for iOS has not been integrated into the Platform API for iOS: https://github.com/apache/cordova-ios/pull/182

**Comment by tony--** [comment]
Right, I wasn't thinking about that - thanks @shazron.  So... is this code here for backwards compatibility?  Or it just hasn't been removed yet?  Sorry for the dumb questions (and dumb PR).

**Comment by shazron** [comment]
no, never dumb it confused me as well at first -- yeah it was for the older platforms. We're trying to clean testing up so its less confusing esp with Platform API breakouts

**Comment by tony--** [comment]
Ok, thanks.  Closing this as an incorrect fix and CB-9311 is being addressed by [apache/cordova-ios#182](https://github.com/apache/cordova-ios/pull/182).

**Pull request closed without merging**
