### PR TITLE
CB-8239 Add support for git urls to 'cordova platform add'

### PR DESCRIPTION
**Pull request by hstaudacher**
A function called 'cordova_custom_git' was added to lazy_load.js. When
invoking 'cordova platform add GIT_REPO' this function will now be
invoked. It clones the repo if accessible into a tmp directory and
forwards the location of this directory to handle it as ordinary folder
after the cloning.

Also two hooks were added: 'before_library_clone' and
'after_library_clone'. They work the same way as the
'before_library_download' and 'after_library_download' hooks.

### CODE REVIEW

**Comment by hstaudacher** [comment]
In issue CB-8239 @omefire suggested 3 features ti be added. This pull request implements one: 'cordova platform add GIT_REPO'

**Comment by hstaudacher** [comment]
I have no idea why the AppVeyor tests are not passing. On my machine and on travis everything seems to be fine. Maybe the fail is unrelated?

**Comment by omefire** [comment]
@hstaudacher, I've added the remaining scenarios.

I've copied over some of the changes you made in this branch and merged them with mine.
I'd be grateful if you could review these changes:

- https://github.com/MSOpenTech/cordova-lib/commit/c1135323c71e2f698e1a9f6fbcbf8d33274b1ff8
- https://github.com/MSOpenTech/cordova-lib/commit/5d4e0e15b09a9cba60e2b5ee423ff528f40c398f
- https://github.com/MSOpenTech/cordova-lib/commit/a8bdc8f7f87294ed8e984728efef7b9f86e9ad8b
- https://github.com/MSOpenTech/cordova-lib/commit/c99eca2bb2712ffaa9a398a2ec48ed59091c072a

**Comment by hstaudacher** [comment]
@omefire I reviewed the change. Looks good to me.

**Comment by omefire** [comment]
I think we don't need this anymore as the functionality this PR wanted to introduce has already been included here : https://github.com/apache/cordova-lib/commit/811f6f72d74dfd2ca054553ae248f0831235f912.  it can be closed.

**Pull request closed without merging**
